FROM python:3.9

RUN apt-get update

# Java Config
RUN apt-get install openjdk-11-jdk -y
ENV JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64

# Python Config
RUN apt-get update
RUN apt-get -y install python3-pip

# Python Dependencies
RUN pip install pyspark
RUN pip install jproperties
RUN pip install redis

CMD [ "/bin/bash" ]